export const SEMANTIC_COMPONENT_TYPES = [
  'cloud',
  'database',
  'server',
  'arrow',
  'button',
  'dashboard',
  'phone',
  'browser',
  'logo',
  'chart',
  'notification',
  'cursor',
  'codeeditor',
  'website',
  'terminal',
  'pricingcard',
  'laptop',
  'editor',
] as const;

export const VECTOR_PROVIDERS = ['phosphor', 'lucide', 'heroicons', 'tabler', 'motionly'] as const;

export type SemanticComponentType = (typeof SEMANTIC_COMPONENT_TYPES)[number];
export type VectorProvider = (typeof VECTOR_PROVIDERS)[number];
export type VectorStyle = 'filled' | 'outline';

export interface SemanticVectorDefinition {
  type: SemanticComponentType;
  provider: VectorProvider;
  icon: string;
  source: string;
  license: 'MIT' | 'ISC' | 'Motionly';
  style: VectorStyle;
  svg: string;
  width: number;
  height: number;
  defaultBehavior: string;
  capabilities: readonly string[];
  layers: readonly string[];
}

const definitions: Record<SemanticComponentType, SemanticVectorDefinition> = {
  cloud: {
    type: 'cloud',
    provider: 'phosphor',
    icon: 'cloud',
    source: 'https://github.com/phosphor-icons/core/blob/main/assets/regular/cloud.svg',
    license: 'MIT',
    style: 'filled',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor"><path d="M160,40A88.09,88.09,0,0,0,81.29,88.67,64,64,0,1,0,72,216h88a88,88,0,0,0,0-176Zm0,160H72a48,48,0,0,1,0-96c1.1,0,2.2,0,3.29.11A88,88,0,0,0,72,128a8,8,0,0,0,16,0,72,72,0,1,1,72,72Z"/></svg>',
    width: 256,
    height: 176,
    defaultBehavior: 'premiumReveal float',
    capabilities: ['float', 'pulse', 'glow', 'receiveData', 'sendData', 'connect'],
    layers: ['glyph', 'glow'],
  },
  database: {
    type: 'database',
    provider: 'lucide',
    icon: 'database',
    source: 'https://github.com/lucide-icons/lucide/blob/main/icons/database.svg',
    license: 'ISC',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5V19A9 3 0 0 0 21 19V5"/><path d="M3 12A9 3 0 0 0 21 12"/></svg>',
    width: 180,
    height: 180,
    defaultBehavior: 'stackReveal pulse',
    capabilities: ['stackReveal', 'pulse', 'glow', 'receiveData', 'sendData', 'connect'],
    layers: ['stack', 'activity'],
  },
  server: {
    type: 'server',
    provider: 'lucide',
    icon: 'server',
    source: 'https://github.com/lucide-icons/lucide/blob/main/icons/server.svg',
    license: 'ISC',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="20" height="8" x="2" y="2" rx="2"/><rect width="20" height="8" x="2" y="14" rx="2"/><line x1="6" x2="6.01" y1="6" y2="6"/><line x1="6" x2="6.01" y1="18" y2="18"/></svg>',
    width: 180,
    height: 180,
    defaultBehavior: 'premiumReveal activate',
    capabilities: ['stackReveal', 'pulse', 'glow', 'receiveData', 'sendData', 'connect'],
    layers: ['chassis', 'status'],
  },
  arrow: {
    type: 'arrow',
    provider: 'tabler',
    icon: 'arrow-right',
    source: 'https://github.com/tabler/tabler-icons/blob/main/icons/outline/arrow-right.svg',
    license: 'MIT',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M13 18l6-6"/><path d="M13 6l6 6"/></svg>',
    width: 180,
    height: 120,
    defaultBehavior: 'draw',
    capabilities: ['draw', 'travel', 'connect', 'followPath', 'guideAttention'],
    layers: ['shaft', 'head'],
  },
  phone: {
    type: 'phone',
    provider: 'heroicons',
    icon: 'device-phone-mobile',
    source:
      'https://github.com/tailwindlabs/heroicons/blob/master/optimized/24/outline/device-phone-mobile.svg',
    license: 'MIT',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" d="M10.5 1.5H8.25A2.25 2.25 0 0 0 6 3.75v16.5a2.25 2.25 0 0 0 2.25 2.25h7.5A2.25 2.25 0 0 0 18 20.25V3.75a2.25 2.25 0 0 0-2.25-2.25H13.5m-3 0V3h3V1.5m-3 0h3m-3 18.75h3"/></svg>',
    width: 150,
    height: 260,
    defaultBehavior: 'screenReveal',
    capabilities: ['screenReveal', 'notification', 'tap', 'glow'],
    layers: ['frame', 'screen', 'status'],
  },
  browser: {
    type: 'browser',
    provider: 'heroicons',
    icon: 'window',
    source: 'https://github.com/tailwindlabs/heroicons/blob/master/optimized/24/outline/window.svg',
    license: 'MIT',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" d="M3 8.25V18a2.25 2.25 0 0 0 2.25 2.25h13.5A2.25 2.25 0 0 0 21 18V8.25m-18 0V6a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 6v2.25m-18 0h18M5.25 6h.008v.008H5.25V6ZM7.5 6h.008v.008H7.5V6Zm2.25 0h.008v.008H9.75V6Z"/></svg>',
    width: 360,
    height: 240,
    defaultBehavior: 'screenReveal',
    capabilities: ['screenReveal', 'highlight', 'cursor', 'connect'],
    layers: ['chrome', 'viewport', 'controls'],
  },
  dashboard: {
    type: 'dashboard',
    provider: 'tabler',
    icon: 'dashboard',
    source: 'https://github.com/tabler/tabler-icons/blob/main/icons/outline/dashboard.svg',
    license: 'MIT',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a2 2 0 1 0 4 0a2 2 0 1 0-4 0"/><path d="M13.45 11.55l2.05-2.05"/><path d="M6.4 20a9 9 0 1 1 11.2 0l-11.2 0"/></svg>',
    width: 300,
    height: 220,
    defaultBehavior: 'dashboardReveal',
    capabilities: ['screenReveal', 'cardStagger', 'chartGrowth', 'count', 'highlight'],
    layers: ['frame', 'cards', 'chart', 'metric', 'highlight'],
  },
  button: {
    type: 'button',
    provider: 'motionly',
    icon: 'action-button',
    source: 'Motionly native semantic vector',
    license: 'Motionly',
    style: 'filled',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 72" fill="currentColor"><path d="M36 0h168a36 36 0 0 1 0 72H36A36 36 0 0 1 36 0Z"/><path fill="#ffffff" d="M112 22l18 14-18 14v-9H92V31h20v-9Z"/></svg>',
    width: 240,
    height: 72,
    defaultBehavior: 'buttonPop',
    capabilities: ['popIn', 'hoverLift', 'clickCompression', 'attentionGlow'],
    layers: ['surface', 'label', 'highlight'],
  },
  logo: {
    type: 'logo',
    provider: 'motionly',
    icon: 'brand-mark',
    source: 'Motionly native fallback; set source to use an imported brand SVG',
    license: 'Motionly',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" stroke="currentColor" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"><path d="M60 8l44 26v52L60 112 16 86V34L60 8Z"/><path d="M16 34l44 28 44-28M60 62v50"/></svg>',
    width: 200,
    height: 200,
    defaultBehavior: 'draw',
    capabilities: ['draw', 'reveal', 'glow', 'morph'],
    layers: ['mark', 'glow'],
  },
  chart: {
    type: 'chart',
    provider: 'lucide',
    icon: 'chart-line',
    source: 'https://github.com/lucide-icons/lucide/blob/main/icons/chart-line.svg',
    license: 'ISC',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 3v16a2 2 0 0 0 2 2h16"/><path d="m19 9-5 5-4-4-3 3"/></svg>',
    width: 520,
    height: 322,
    defaultBehavior: 'chartGrowth',
    capabilities: ['chartGrowth', 'count', 'highlight', 'connect'],
    layers: ['panel', 'axis', 'bars', 'line', 'metric'],
  },
  notification: {
    type: 'notification',
    provider: 'lucide',
    icon: 'bell',
    source: 'https://github.com/lucide-icons/lucide/blob/main/icons/bell.svg',
    license: 'ISC',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"/><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/></svg>',
    width: 420,
    height: 110,
    defaultBehavior: 'popIn',
    capabilities: ['popIn', 'reactsTo', 'glow', 'dismiss'],
    layers: ['card', 'stripe', 'icon', 'copy'],
  },
  cursor: {
    type: 'cursor',
    provider: 'lucide',
    icon: 'mouse-pointer',
    source: 'https://github.com/lucide-icons/lucide/blob/main/icons/mouse-pointer.svg',
    license: 'ISC',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m3 3 7.07 16.97 2.51-7.39 7.39-2.51L3 3z"/><path d="m13 13 6 6"/></svg>',
    width: 44,
    height: 44,
    defaultBehavior: 'moveTo',
    capabilities: ['moveTo', 'click', 'ripple'],
    layers: ['pointer', 'ripple'],
  },
  codeeditor: {
    type: 'codeeditor',
    provider: 'lucide',
    icon: 'code',
    source: 'https://github.com/lucide-icons/lucide/blob/main/icons/code.svg',
    license: 'ISC',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>',
    width: 680,
    height: 422,
    defaultBehavior: 'typeIn',
    capabilities: ['typeIn', 'screenReveal', 'highlight', 'connect'],
    layers: ['frame', 'titlebar', 'lines', 'status'],
  },
  website: {
    type: 'website',
    provider: 'lucide',
    icon: 'globe',
    source: 'https://github.com/lucide-icons/lucide/blob/main/icons/globe.svg',
    license: 'ISC',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/></svg>',
    width: 720,
    height: 460,
    defaultBehavior: 'screenReveal',
    capabilities: ['screenReveal', 'highlight', 'cursor', 'connect'],
    layers: ['frame', 'nav', 'hero', 'cta', 'banner'],
  },
  terminal: {
    type: 'terminal',
    provider: 'lucide',
    icon: 'terminal',
    source: 'https://github.com/lucide-icons/lucide/blob/main/icons/terminal.svg',
    license: 'ISC',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="4 17 10 11 4 5"/><line x1="12" x2="20" y1="19" y2="19"/></svg>',
    width: 640,
    height: 384,
    defaultBehavior: 'typeIn',
    capabilities: ['typeIn', 'progress', 'connect'],
    layers: ['frame', 'titlebar', 'prompt', 'progress', 'status'],
  },
  pricingcard: {
    type: 'pricingcard',
    provider: 'lucide',
    icon: 'gem',
    source: 'https://github.com/lucide-icons/lucide/blob/main/icons/gem.svg',
    license: 'ISC',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 3h12l4 6-10 13L2 9Z"/><path d="M11 3 8 9l4 13 4-13-3-6"/><path d="M2 9h20"/></svg>',
    width: 380,
    height: 470,
    defaultBehavior: 'popIn',
    capabilities: ['popIn', 'count', 'highlight'],
    layers: ['card', 'plan', 'price', 'features', 'cta'],
  },
  laptop: {
    type: 'laptop',
    provider: 'lucide',
    icon: 'laptop',
    source: 'https://github.com/lucide-icons/lucide/blob/main/icons/laptop.svg',
    license: 'ISC',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 16V7a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v9m16 0H4m16 0 1.28 2.55a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45L4 16"/></svg>',
    width: 760,
    height: 500,
    defaultBehavior: 'screenReveal',
    capabilities: ['screenReveal', 'highlight', 'cursor', 'connect'],
    layers: ['lid', 'screen', 'nav', 'hero', 'cta', 'base'],
  },
  editor: {
    type: 'editor',
    provider: 'motionly',
    icon: 'motionly-editor',
    source: 'Motionly native workspace component',
    license: 'Motionly',
    style: 'outline',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="20" height="16" x="2" y="4" rx="2"/><path d="M2 8h20"/><path d="M6 12h6"/><path d="M6 16h10"/></svg>',
    width: 1200,
    height: 672,
    defaultBehavior: 'screenReveal',
    capabilities: ['screenReveal', 'typeIn', 'cardStagger', 'chartGrowth', 'count', 'highlight'],
    layers: ['frame', 'rail', 'topbar', 'canvas', 'timeline', 'panel', 'draft'],
  },
};

export function isSemanticComponentType(value: string): value is SemanticComponentType {
  return (SEMANTIC_COMPONENT_TYPES as readonly string[]).includes(value);
}

export function vectorDefinition(type: SemanticComponentType): SemanticVectorDefinition {
  return definitions[type];
}

export function semanticVectorDefinitions(): readonly SemanticVectorDefinition[] {
  return Object.values(definitions);
}

export function svgDataUri(source: string): string {
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(source)}`;
}
